Geumcheon.Web.Consult/Controllers/ScoreController.cs
using Geumcheon.Web.Consult.Models;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Geumcheon.Web.Consult.Controllers
{
    public class ScoreController : Controller
    {
        // GET: Score
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult BasicInfo()
        {
            return View();
        }

        public ActionResult Moi()
        {
            return View();
        }

        public ActionResult Nesin()
        {
            return View();
        }



        [HttpPost]
        public JsonResult ModifyAnswer(string writerType, string answer)
        {
            Answer model = new Answer
            {
                MemberIdx  = 1
            ,   WriterType = writerType
            ,   AnswerJson = answer
            };
            int result = ConsultRepository.Instance.SetAnswer(model);

            if (result > 0)
            {
                return Json(new { ok = true });
            }
            else
            {
                return Json(new { ok = false });
            }
        }

        [HttpPost]
        public JsonResult ModifyUniversityitem(string writerType, string univItemJson)
        {
            DataTable dtUnivItem = JsonConvert.DeserializeObject<DataTable>(univItemJson);
            ApplyUniversity model = new ApplyUniversity
            {
                MemberIdx = 1
            ,   WriterType = writerType
            ,   tbUnivesity = dtUnivItem
            };            

            int result = ConsultRepository.Instance.SetApplyUniversity(model);
            if (result > 0)
            {
                return Json(new { ok = true });
            }
            else
            {
                return Json(new { ok = false });
            }
        }
    }
}

Geumcheon.Web.Consult/Views/Score/BasicInfo.cshtml
@using Geumcheon.Web.Consult.Models
@model Application
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<style>
    th {
        font-weight: bold !important;
    }
</style>
<script>
    $(document).ready(function () {

    });

    fnSave = function () {
        var isValudation = true;
        var answerArray = new Array();
        $.each($(".student").find(".answer"), function (key, value) {

            var id = $(this).attr("id");
            var answer = $(this).val();

            var answerInfo = new Object();
            answerInfo.ID = id;
            answerInfo.Answer = answer;
            answerArray.push(answerInfo);
        });


        if (isValudation) {
            var answerItem = new Object();
            answerItem.AnswerItem = answerArray
            var answerJson = JSON.stringify(answerArray);
            //fnSetResponse(answerJson);
            fnSaveAnswer('S', answerJson);
            //var obj2 = JSON.parse(answerJson);
            //$.each(obj2, function (key, value) {
            //    alert(value.ID);
            //    alert(value.Answer);
            //});
        }
    };

    fnUnivItemSave = function () {
        var univItemArray = new Array();
        $.each($(".univ-item"), function (key, value) {

            var apply_univ_idx = $(this).attr("idx");
            var ranking = $(this).attr("ranking");
            var university_name = $(this).find(".univ").val();
            var stype_rem = $(this).find(".stype-rem").val();
            var major_name = $(this).find(".major-name").val();

            var UnivItem = new Object();

            UnivItem.ApplyUnivIdx = parseInt(apply_univ_idx);
            UnivItem.Ranking = parseInt(ranking);
            UnivItem.UniversityName = university_name
            UnivItem.StypeRem = stype_rem
            UnivItem.MajorName = major_name
            univItemArray.push(UnivItem);
        });

        //$.each(univItemArray, function (key, value) {
        //    alert(value.Ranking);
        //    alert(value.UniversityName);
        //    alert(value.StypeRem);
        //    alert(value.MajorName);
        //});
        var univJson = JSON.stringify(univItemArray);
        fnModifyUnivItem("S", univJson);

    }

    fnSaveAnswer = function (writerType, answer) {
        var date = $("#dteConsultDate").val();
        var ableTimes = '';
        $.ajax({
            type: "POST",
            contentType: "application/json; charset=UTF-8",
            dataType: "json",
            data: JSON.stringify({
                'writerType': writerType
                , 'answer': answer
            }),
            url: '@Url.Action("ModifyAnswer", "Score")',
            success: function (msg) {
                var result = msg.ok;
                if (result) {
                    alert('저장성공');
                }
                else {
                    alert('저장실패')
                }
            },
            error: function (xhr, msg) { alert(msg); },
        });
    }

    fnModifyUnivItem = function (writerType, univitem) {
        var date = $("#dteConsultDate").val();
        var ableTimes = '';
        $.ajax({
            type: "POST",
            contentType: "application/json; charset=UTF-8",
            dataType: "json",
            data: JSON.stringify({
                  'writerType': writerType
                , 'univItemJson': univitem
            }),
            url: '@Url.Action("ModifyUniversityitem", "Score")',
            success: function (msg) {
                var result = msg.ok;
                if (result) {
                    alert('저장성공');
                }
                else {
                    alert('저장실패')
                }
            },
            error: function (xhr, msg) { alert(msg); },
        });
    }
</script>

<div class="common_form">
    <div class="student">
        <table class="form_tbl">

            <tbody>
                <tr>
                    <td colspan="4">지원희망대학</td>
                </tr>
                <tr class="univ-item" ranking="1" idx="0">
                    <td>
                        1지망
                    </td>
                    <td>
                        <input type="text" class="univ" />대학
                    </td>
                    <td>
                        <input type="text" class="stype-rem" />전형
                    </td>
                    <td>
                        <input type="text" class="major-name" />학과
                    </td>
                </tr>
                <tr class="univ-item" ranking="2" idx="0">
                    <td>
                        2지망
                    </td>
                    <td>
                        <input type="text" class="univ" />대학
                    </td>
                    <td>
                        <input type="text" class="stype-rem" />전형
                    </td>
                    <td>
                        <input type="text" class="major-name" />학과
                    </td>
                </tr>
                <tr class="univ-item" ranking="3" idx="0">
                    <td>
                        3지망
                    </td>
                    <td>
                        <input type="text" class="univ" />대학
                    </td>
                    <td>
                        <input type="text" class="stype-rem" />전형
                    </td>
                    <td>
                        <input type="text" class="major-name" />학과
                    </td>
                </tr>

            </tbody>
        </table>

        <table class="form_tbl">
            <tr>
                <td rowspan="3">
                    학습
                </td>
                <td>
                    제일 어렵거나 힘든과목
                </td>
                <td><input type="text" id="s_a1" class="answer" /></td>
            </tr>
            <tr>
                <td>위의 과목 공부가 힘든 이유가 무엇인가요?</td>
                <td><input type="text" id="s_a2" class="answer" /></td>
            </tr>
            <tr>
                <td>그 외의 과목에서 어려움이 무엇인가요?</td>
                <td><input type="text" id="s_a3" class="answer" /></td>
            </tr>

            <tr>
                <td>진학</td>
                <td>진학방면으로 고민 되는 도움받고 싶은 부분을 자세하게 작성해주세요</td>
                <td><input type="text" id="j_a1" class="answer" /></td>
            </tr>
            <tr>
                <td rowspan="3">진로</td>
                <td>앞으로 어떤 직업을 갖고 싶은가요?</td>
                <td><input type="text" id="c_a1" class="answer" /></td>
            </tr>
            <tr>
                <td>
                    위의 직업을 갖고 싶은 이유를 적어주세요
                </td>
                <td><input type="text" id="c_a2" class="answer" /></td>
            </tr>
            <tr>
                <td>
                    진로에 대한 고민이 있다면 적어주세요
                </td>
                <td><input type="text" id="c_a3" class="answer" /></td>
            </tr>
            <tr>
                <td rowspan="2">생활</td>
                <td>생활하면서 요즘 가장 고민되는 부분은?</td>
                <td><input type="text" id="l_a1" class="answer" /></td>
            </tr>
            <tr>
                <td>고치고싶은 습관이 있다면?</td>
                <td><input type="text" id="l_a2" class="answer" /></td>
            </tr>
            <tr>
                <td rowspan="2">기타</td>
                <td>현재 다니고 있는 학원/과목 기타사항을 적어주세요</td>
                <td><input type="text" id="e_a1" class="answer" /></td>
            </tr>
            <tr>
                <td>현재 다니고 있는 학원/과목 기타사항을 적어주세요</td>
                <td><input type="text" id="e_a1" class="answer" /></td>
            </tr>
        </table>
    </div>

    <div class="btn_a right no-print">
        <a href="#" class="btn blue" style="padding:0px;" onclick="fnUnivItemSave();">저장하기</a>
    </div>
</div>

Geumcheon.Web.Consult/Views/Score/Nesin.cshtml
@using Geumcheon.Web.Consult.Models
@model Application
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<style>
    th {
        font-weight: bold !important;
    }
</style>
<script>
    $(document).ready(function () {

    });
</script>

<div class="common_form">
    <div class="student">
        <table class="form_tbl">

            <tbody>
                <tr>
                    <td colspan="2">
                        구분
                    </td>
                    <td>
                        1학년
                    </td>
                    <td>
                        2학년
                    </td>
                    <td>
                        3학년
                    </td>
                    <td>평군</td>
                </tr>
                <tr>
                    <td rowspan="5">
                        석차등급
                    </td>
                    <td>
                        국어
                    </td>
                    <td>
                        <span class="avrg_k"></span>
                    </td>
                    <td>
                        <span class="avrg_k"></span>
                    </td>
                    <td>
                        <span class="avrg_k"></span>
                    </td>
                    <td><input type="text" /></td>
                </tr>
                <tr>
                    <td>
                        영어
                    </td>
                    <td>
                        <span class="avrg_e"></span>
                    </td>
                    <td>
                        <span class="avrg_e"></span>
                    </td>
                    <td>
                        <span class="avrg_e"></span>
                    </td>
                    <td><input type="text" /></td>
                </tr>
                <tr>
                    <td>
                        수학
                    </td>
                    <td>
                        <span class="avrg_m"></span>
                    </td>
                    <td>
                        <span class="avrg_m"></span>
                    </td>
                    <td>
                        <span class="avrg_m"></span>
                    </td>
                    <td><input type="text" /></td>
                </tr>
                <tr>
                    <td>
                        사회
                    </td>
                    <td>
                        <span class="avrg_soc"></span>
                    </td>
                    <td>
                        <span class="avrg_soc"></span>
                    </td>
                    <td>
                        <span class="avrg_soc"></span>
                    </td>
                    <td><input type="text" /></td>
                </tr>
                <tr>
                    <td>
                        과학
                    </td>
                    <td>
                        <span class="avrg_sci"></span>
                    </td>
                    <td>
                        <span class="avrg_sci"></span>
                    </td>
                    <td>
                        <span class="avrg_sci"></span>
                    </td>
                    <td><input type="text" /></td>
                </tr>

            </tbody>
        </table>
    </div>

    <div class="btn_a right no-print">
        <a href="#" class="btn blue" style="padding:0px;" onclick="fnUnivItemSave();">저장하기</a>
    </div>
</div>