Geumcheon.Web.Consult/Models/Reply.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Geumcheon.Web.Consult.Models
{
    public class Reply
    {
        public int ApplicationIdx { get; set; }
        public int TeacherIdx { get; set; }
        public string Note { get; set; }
        public string ReplyNote { get; set; }
        public string Progress { get; set; }


        public string ProgressName
        {
            get
            {
                string rVal = string.Empty;
                switch (Progress)
                {
                    case "R":
                        {
                            rVal = "대기중";
                            break;
                        }
                    case "I":
                        {
                            rVal = "작성중";
                            break;
                        }
                    case "C":
                        {
                            rVal = "상담완료";
                            break;
                        }
                }
                return rVal;
            }
        }

        public DateTime ReplyDate { get; set; }
    }
}

Geumcheon.Web.Consult/Controllers/EntranceController.cs
using Geumcheon.Web.Consult.Models;
using Geumcheon.Web.Core.Entity;
using Geumcheon.Web.Core.Repository;
using Geumcheon.Web.Core.ViewModel;
using Microsoft.AspNet.Identity;
using Microsoft.Owin.Security;
using Newtonsoft.Json.Linq;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.IO;
using System.Linq;
using System.Security.Claims;
using System.Text;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;
using System.Web.UI;
using System.Web.UI.WebControls;
using DocumentFormat.OpenXml.Packaging;
using DocumentFormat.OpenXml.Spreadsheet;
using Geumcheon.Web.Consult.App_Start;
using System.Threading;

namespace Geumcheon.Web.Consult.Controllers
{
    public class EntranceController : Controller
    {
        static string _COMPANY_CODE = "0001";
        static int _PAGESIZE = 15;

        #region View

        // GET: Application
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Info(string way = "I", int eidx = 3)
        {
            ViewBag.ConsultWay = way;
            Entrance entrance = EntranceRequestRepository.Instance.EntranceInfoSelect(eidx);
            if (entrance == null)
            {
                entrance = new Entrance
                {
                    EntranceIdx = eidx
                };
            }
            return PartialView(entrance);
        }

        public ActionResult Consult(string way = "I", int eidx = 4, int page = 1, SearchInfo searchInfo = null)
        {
            try
            {

                if (way.ToUpper() == "O")
                {
                    eidx = 1;
                }
                else if (way.ToUpper() == "V")
                {
                    eidx = 2;
                }
                //else
                //{

                //}

                int rVal = EntranceRequestRepository.Instance.EntranceSelect(way,eidx);
                ViewBag.ConsultWay = way;
                ViewBag.Page = page;
                ViewBag.Title = SetTitle(way);
                ViewBag.Navigation = SetNavigation(way);
                ViewBag.EntranceCnt = rVal;
                ViewBag.EntranceIdx = eidx;
                return View();
            }
            catch (Exception ex)
            {
                if (way.ToUpper() == "O")
                {
                    eidx = 1;
                }
                else if (way.ToUpper() == "V")
                {
                    eidx = 2;
                }
                //else
                //{

                //}

                ViewBag.ConsultWay = way;
                ViewBag.Page = page;
                ViewBag.Title = SetTitle(way);
                ViewBag.Navigation = SetNavigation(way);
                ViewBag.EntranceIdx = eidx;

                return View();
            }
        }

        [FPAuthorize(Roles = "GEUMCHEON")]
        public ActionResult Detail(int requestIdx)
        {
            if (_identity.Roll == "CONSULT")
            {
                var item = EntranceRequestRepository.Instance.EntranceRequestSelectItem(requestIdx);
                var member = MemberRepository.Instance.MemberSelectItem(item.member.ID);
                var entrance = EntranceRequestRepository.Instance.EntranceInfoSelect(item.EIdx);
                item.DisplayInputType = entrance?.DisplayInputType;

                if (member != null)
                {
                    ViewData["Member"] = member;
                }
                else
                {
                    ViewData["Member"] = new Geumcheon.Web.Core.Entity.Member();
                }
                    
                ViewBag.Title = SetTitle(item.ConsultWay);

                return View(item);
            }
            else
            {
                try
                {
                    var member = MemberRepository.Instance.MemberSelectItem(_identity.ConsultId);
                    if (member != null)
                    {
                        ViewData["Member"] = member;
                    }
                    else
                    {
                        ViewData["Member"] = new Geumcheon.Web.Core.Entity.Member();
                    }

                    var item = EntranceRequestRepository.Instance.EntranceRequestSelectItem(requestIdx);
                    var entrance = EntranceRequestRepository.Instance.EntranceInfoSelect(item.EIdx);
                    item.DisplayInputType = entrance?.DisplayInputType;
                    if (!item.member.ID.Equals(_identity.ConsultId))
                    {
                        throw new HttpException(401, "unauthorized");
                    }
                    ViewBag.Title = SetTitle(item.ConsultWay);

                    return View(item);
                }
                catch(Exception ex)
                {
                    if (ex.Message == "unauthorized")
                    {
                        return Redirect("/Error/err?status=401");
                    }
                    else
                    {
                        return View(new EntranceRequest());
                    }
                }                
            }            
        }

        public ActionResult Intro()
        {
            return View();
        }

        [FPAuthorize(Roles = "GEUMCHEON")]
        public ActionResult Modify(string way = "I",int requestIdx = 0, int eidx = 0)
        {
            ViewBag.ConsultWay = way;
            ViewBag.Title = SetTitle(way);
            ViewBag.EntranceIdx = eidx;
            var member = MemberRepository.Instance.MemberSelectItem(_identity.ConsultId);
            var entrance = EntranceRequestRepository.Instance.EntranceInfoSelect(eidx);
            if (member != null)
            {
                ViewData["Member"] = member;
            }
            else
            {
                ViewData["Member"] = new Geumcheon.Web.Core.Entity.Member();
            }

            if (requestIdx != 0)
            {
                var item = EntranceRequestRepository.Instance.EntranceRequestSelectItem(requestIdx);                
                ViewBag.ConsultWay = item.ConsultWay;
                item.DisplayInputType = entrance?.DisplayInputType;

                return View(item);
            }
            else
            {
                return View(new EntranceRequest { DisplayInputType = entrance?.DisplayInputType });
            }
        }        
        [FPAuthorize(Roles = "GEUMCHEON")]
        public ActionResult StudentInfo(string idx, string requestIdx)
        {
            if (_identity.Roll == "CONSULT")
            {
                var item = EntranceRequestRepository.Instance.EntranceRequestSelectItem(int.Parse(requestIdx));
                var member = MemberRepository.Instance.MemberSelectItemForConsult(item.member.ID, requestIdx);
                if (member != null)
                {
                    ViewData["Member"] = member;
                }
                else
                {
                    ViewData["Member"] = new Geumcheon.Web.Core.Entity.Member();
                }

                ViewBag.MemberIdx = idx;
                return View(item);
            }
            else
            {
                throw new HttpException(401, "Unauthorized access");
            }
        }

        [FPAuthorize(Roles = "GEUMCHEON")]
        public ActionResult SmartTestReport(string memberIdx)
        {
            string stuIdx = MyPageRepository.Instance.GetReportLinkCode("600", memberIdx);
            if(string.IsNullOrEmpty(stuIdx) || stuIdx.Equals("0"))
            {
                return Content("<script language='javascript' type='text/javascript'>alert('검사를 완료하지 않았습니다');</script>");
            }
            else
            {
                
                return Redirect("http://psy.futureplan.co.kr/Report/rptcs?stuIdx=" + stuIdx);
            }
        }

        #endregion


        #region AJAX

        [HttpPost]
        [FPAuthorize(Roles = "GEUMCHEON")]
        public JsonResult RequestConsult()
        {            
            JObject model = JObject.Parse(new System.IO.StreamReader(Request.InputStream).ReadToEnd());
            string consultType = model.SelectToken("type")?.Value<string>() ?? "I";

            int requestIdx, scheduleTimeIdx,eidx = 0;
            int.TryParse(model.SelectToken("consulttime")?.Value<string>(), out scheduleTimeIdx);
            int.TryParse(model.SelectToken("requestidx").Value<string>(), out requestIdx);
            int.TryParse(model.SelectToken("eidx").Value<string>(), out eidx);
            if (consultType == "V")
            {
                List<ScheduleTime> rVal = ConsultRepository.Instance.GetScheduleTime(_COMPANY_CODE, model.SelectToken("consultdate")?.Value<string>(), _identity.SchoolType);
                if (rVal != null && requestIdx == 0 && (rVal.Where(x => x.ConsultTimeIdx == scheduleTimeIdx).FirstOrDefault()?.Cnt ?? -1) < 1)
                {
                    return Json(new
                    {
                        ok = false,
                        message = "해당 희망 날짜에 좌석이 없습니다."
                    });
                }
            }

            Geumcheon.Web.Core.Entity.Member member = new Geumcheon.Web.Core.Entity.Member
            {
                ID = _identity.ConsultId,
                Name = model.SelectToken("name")?.Value<string>(),
                Hp = model.SelectToken("hp")?.Value<string>(),
                Email = model.SelectToken("email")?.Value<string>(),
                School = model.SelectToken("school")?.Value<string>(),
                Grade = model.SelectToken("grade")?.Value<int>() ?? 1,
                IsUse = true,
            };

            string studentName = model.SelectToken("studentname").Value<string>();
            int gender = model.SelectToken("gender")?.Value<int>() ?? 1;

Geumcheon.Web.Consult/Views/Entrance/Consult.cshtml
@model Geumcheon.Web.Core.ViewModel.ViewModelList<Geumcheon.Web.Core.Entity.Application, Geumcheon.Web.Core.ViewModel.SearchInfo>
@{
    Layout = "~/Views/Shared/_Layout.cshtml";

    Geumcheon.Web.Core.Entity.Member member = ViewData["Member"] as Geumcheon.Web.Core.Entity.Member;

    ViewBag.Title = ViewBag.ConsultWay == "I" ? "정시컨설팅" : (ViewBag.ConsultWay == "V" ? "종합컨설팅" : "온라인컨설팅");
}


@if (!string.IsNullOrEmpty(Geumcheon.Web.Consult.Models._identity.TeacherIdx))
{
    @section Javascript {
        <script src="~/Resources/js/fpLib.js"></script>
        <script type="text/javascript">
            var duplicateCheckID = "";
            var requesting = false;

            $(document).ready(function () {
                // 검색
                $("#modifyBtn").on("click", function () {
                    requestConsultList(@ViewBag.Page);
                });

                // 검색창 입력창 엔터
                $("#searchTitle").on("keydown", function (key) {
                    if (key.keyCode == 13) {
                        requestConsultList(@ViewBag.Page);
                    }
                });

                requestConsultList(@ViewBag.Page);
            });

            // 상담 신청 리스트 조회
            var requestConsultList = function (page) {
                $.ajax({
                    url: "@Url.Action("RequestList", "Entrance")",
                    headers: {
                        "Content-Type":"application/json"
                    },
                    data: JSON.stringify({
                        page : page,
                        type: "@(ViewBag.ConsultWay ?? "I")",
                        search: $("#searchTitle").val(),
                        order: "REGDATE"
                    }),
                    dataType: "json",
                    type: "POST",
                    beforeSend: function () {
                        requesting = true
                    }
                }).done(function (json) {
                    console.log(json);
                    createConsultList(json.data);
                    requesting = false;
                }).fail(function (httpObj, textStatus) {
                    requesting = false;
                    alert("처리 중 오류가 발생하였습니다.");
                });
            }


        </script>
    }
    @section Css
{
        <style>
            .consultlist .row > div:nth-child(n) {
                width: 20%;
                padding: 8px;
            }

            .consultlist .row > div:first-child {
                width: 5%;
                padding: 8px;
            }

            .consultlist .row > div:last-child {
                width: 15%;
                padding: 8px;
            }
        </style>
    }


    <div style="min-width:960px;">
        <div class="content">
            <!-- 신청 내역 -->
            <div name="list">
                <div style="padding:24px 8px 8px 8px;">
                    <h1 style="padding:0px 8px;">| 주의사항 |</h1>
                    <div class="registerdata">
                        <span>
                            승인대기 : 신청이 접수 된 상태입니다.<br />
                            신청승인 : 접수 된 신청에 대해 상담 선생님이 배정 된 상태입니다.<br />
                            상담완료 : 상담이 완료 된 상태입니다.<br />
                        </span>
                    </div>
                </div>
                <div class="registerform">
                    <div class="divider"></div>

                    <div class="divider"></div>
                    <div>
                        <div style="display:flex; align-items:center; text-align:center; border: 1px solid #C3C3C3; border-top: 1px solid #3685ca; background-color:#F7F7F7; font-weight:bold;">
                            <div style="width:5%;padding:8px; border-right:1px solid #C3C3C3;">번호</div>
                            <div style="width:20%;padding:8px; border-right:1px solid #C3C3C3;">제목</div>
                            <div style="width:20%;padding:8px; border-right:1px solid #C3C3C3;">신청자 이름</div>
                            <div style="width:20%;padding:8px; border-right:1px solid #C3C3C3;">신청일</div>
                            <div style="width:20%;padding:8px; border-right:1px solid #C3C3C3;">상담희망일</div>
                            <div style="width:15%;padding:8px;">상태</div>
                        </div>
                        <div class="consultlist">
                        </div>
                        <div class="divider"></div>
                        <div id="pager" style="margin-top:5px;">
                            <div class="totalCount">
                                전체 <span style="font-weight:bold; color:#428bca;"></span> 건
                            </div>
                            <div class="pagination-container" style="text-align:center;">
                                <ul class="pagination"></ul>
                            </div>
                        </div>
                    </div>
                    <div class="divider"></div>
                </div>
            </div>
        </div>
    </div>
}
else
{
    <link href="~/Resources/css/info_style.css" rel="stylesheet" />
    @section Javascript {
        <script type="text/javascript">
            var duplicateCheckID = "";
            var requesting = false;

            const phoneRegex = /^01(?:0|1|[6-9])[.-]?(\d{3}|\d{4})[.-]?(\d{4})$/;
            const emailRegex = /^(([^<>()\[\].,;:\s@@"]+(\.[^<>()\[\].,;:\s@@"]+)*)|(".+"))@@(([^<>()[\].,;:\s@@"]+\.)+[^<>()[\].,;:\s@@"]{2,})$/i;

            $(document).ready(function () {
                // 컨설팅 정보 불러오기
                $.ajax({
                type: "GET",
                    url: "@Url.Action("Info", "Entrance")" + "?way=@ViewBag.ConsultWay&eidx=@ViewBag.EntranceIdx",
                    contentType: "application/json",
                    beforeSend: function () {

                    },
                    complete: function () {

                    },
                    success: function (data) {
                        if (data.message != null) {
                            alert(data.message);
                        }
                        else {
                            $("div[name=info]").html(data);
                        }
                        return;
                    },
                    error: function (msg) {
                        alert("AjaxHtml Error : " + msg.responseText);
                    }
                });

                //신청
                $("#requestBtn").on("click", function () {
                    if ($(this).hasClass("grey")) {
                        alert('신청기간이 아닙니다');
                    }
                    else {
                        if ("@Geumcheon.Web.Consult.Models._identity.ConsultId" == "") {
                            alert("로그인 후 신청 가능합니다.\r\n로그인 화면으로 이동합니다.");
                            location.href = "@Url.Action("Login", "Account")?returnUrl=@this.Request.Url.PathAndQuery";
                        }
                        else {
                            if (@((ViewBag.ConsultWay == "I" && ViewBag.EntranceCnt <= -10 && ViewBag.EntranceCnt > -9999) ? 1 : 0)) {

                                msgPopupShow(true);
                                return;
                            }

                            if ('@ViewBag.ConsultWay' == 'O"') {
                                location.href = "./Modify?way=@ViewBag.ConsultWay&eidx=@ViewBag.EntranceIdx";
                            }
                            else {
                                location.href = "./Modify?way=@ViewBag.ConsultWay&eidx=@ViewBag.EntranceIdx";
                            }
                        }
                    }
                });

                $("#msgModalLeftBtn").on("click", function () {
                    location.href = "@(Url.Action("Consult", "Entrance") + "?way=V&eidx=" + ViewBag.EntranceIdx)";
                });

                $("#msgModalRightBtn").on("click", function () {
                    location.href = "@(Url.Action("Modify", "Entrance") + "?way=" + ViewBag.ConsultWay + "&eidx=" + ViewBag.EntranceIdx)";
                });
            });

            var msgPopupShow = function (value) {
                if (value) {
                    $("#msgModal")[0].style.display = "block";
                }
                else {
                    $("#msgModal")[0].style.display = "none";
                }
            }
        </script>
    }
    @section Css
    {
        <style>
            .dateBox input.text.Ty2 {
                height: 38px !important;
                width: 160px;
            }

            .socre input[type=text] {
                width: 100% !important;
            }

            .InnerTable {
                border: 1px solid #808080;
                border-collapse: collapse;
            }

                .InnerTable td {
                    border: 1px solid #060606;
                    text-align: center;
                    width: 100px;
                    height: 30px;
                }

                    .InnerTable td.T {
                        background-color: #e5fbf4;
                        font-weight: bold;
                        color: #333;
                    }

                    .InnerTable td.N {
                        background-color: #f7f6dc;
                        font-weight: bold;
                        color: #333;
                    }

                    .InnerTable td.H {
                        background-color: #f7e8ea;
                        font-weight: bold;
                        color: #333;
                    }
        </style>
    }

    <div style="min-width:960px;">
        <div class="content">
            <div name="info" style="padding:24px 8px 8px 8px;"></div>
            <hr />
            <!-- 컨설트 신청 -->
            @if (ViewBag.ConsultWay == "O")
            {
                <div>
                    @Html.Partial("../Shared/Partial/_List")
                </div>
            }
            <hr />
            <div name="request">
                <div>
                    @if (ViewBag.EntranceCnt <= 0 && ViewBag.EntranceCnt > -9999)
                    {
                        <div style="margin-left:30px; color:red;">* 모집인원 수가 초과되었을 경우, 아래의 신청하기 버튼은 '대기신청'버튼으로 변경됩니다. '대기신청'에도 신청은 가능하며, 취소인원이 있을 때 담당자가 연락을 드립니다.</div>
                    }
                    <div class="registerrow">
                        <div class="registerdata" style="margin:auto;">
                            <div class="btns" style="margin-left:8px;">
                                @if (ViewBag.EntranceCnt == -9999)
                                {
                                    <a class="btn grey" id="requestBtn" style="font-size:20px; padding:8px 32px;">신청하기</a>
                                }
                                else if (ViewBag.EntranceCnt <= 0)
                                {
                                    <a class="btn blue" id="requestBtn" style="font-size:20px; padding:8px 32px;">대기신청</a>
                                }
                                else
                                {
                                    <a class="btn blue" id="requestBtn" style="font-size:20px; padding:8px 32px;">신청하기</a>
                                }

                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div id="msgModal" style="position:fixed; top:50%; left:50%; transform:translate(-50%, -50%); width:100%; height:100%; background-color:rgba(0,0,0,0.5); display:none;" onclick="msgPopupShow(false)">
        <div style="width:500px; height:320px; position:fixed; top:50%; left:50%; transform:translate(-50%, -50%); background-color:#fff; border-radius:8px;">
            <div style="padding:8px; border-bottom:2px solid #dadada;font-size:24px; font-weight:600; text-align:center;">
                알림
            </div>
            <div style="padding:8px;">
                <div style="font-size:24px;">
                    대면컨설팅은 마감되었습니다.
                </div>
                <br />
                <div style="font-size:18px;">
                    화상컨설팅을 신청해주세요.
                </div>
                <div style="font-size:18px;">
                    대면과 화상의 상담시간, 내용에는 차이가 없고, 오히려 화상 컨설팅의 만족도가 높습니다.
                </div>
                <div style="font-size:18px; color:red;">
                    본 행사는 코로나19로 인해 화상컨설팅으로 변경될 수 있습니다
                </div>               
            </div>
            <div style="position:fixed; bottom:0px; text-align:center; width:100%; display:flex;">
                <div class="btns" style="padding:8px;flex-grow:1">
                    <a class="btn orange" id="msgModalLeftBtn" style="font-size:18px; padding:8px 32px;">화상컨설팅 신청가기</a>
                </div>
            </div>
        </div>
    </div>
}

Geumcheon.Web.Consult/Views/Entrance/List.cshtml
@model Geumcheon.Web.Core.ViewModel.ViewModelList<Geumcheon.Web.Core.Entity.Application, Geumcheon.Web.Core.ViewModel.SearchInfo>
@{
    ViewBag.Title = "상담신청";
    Layout = "~/Views/Shared/_Layout.cshtml";

    Geumcheon.Web.Core.Entity.Member member = ViewData["Member"] as Geumcheon.Web.Core.Entity.Member;
}

<script src="~/Resources/js/fpLib.js"></script>
<script>
    $(document).ready(function () {
        $(".datepicker").datepicker({ dateFormat: "yy-mm-dd" });

        //alert($("#dteConsultStartDate").val());
        $("#btn-down-excel").click(function () {
            var startDt = $("#dteConsultStartDate").val();
            var endDt = $("#dteConsultStartDate").val();
            location.href = "ExcelDownLoad?s=" + startDt + "&e=" + endDt;
            //alert($("#dteConsultStartDate").val());
            //alert($("#dteConsultEndDate").val());
        })
    })
</script>
<div>

</div>

<div class="content" style="min-width:1280px; max-width:1280px;">
    <!-- 신청 내역 -->
    <div name="list">
        <div style="padding:24px 8px 8px 8px; background-color:#f9f8f8; margin-bottom:10px;">
            @if (Geumcheon.Web.Consult.Models._identity.Roll == "CONSULT")
            {
                @Html.Partial("../Shared/Partial/_Info_C")
            }
            else
            {
                @Html.Partial("../Shared/Partial/_Info_S")
            }

        </div>

        @if (Geumcheon.Web.Consult.Models._identity.Roll == "CONSULT" && ViewBag.ConsultWay != "O")
        {

            <div style="float:left; width:100%; margin-bottom:5px; padding:20px; background-color:#f9f8f8;">
                <div class="dateBox" style="width:25%; margin-bottom:5px;float:left;">
                    <span style="font-weight:bold;"> 상담시작일 : </span><input type="text" id="dteConsultStartDate" readonly="readonly" class="datepicker date text Ty2"
                                                                           style="width:198px;" placeholder="날짜를 선택하세요" /><br />
                </div>
                <div style="float:left;">~</div>
                <div class="dateBox" style="width:25%; margin-bottom:5px;float:left;">
                    <span style="font-weight:bold;"> 상담종료일 : </span><input type="text" id="dteConsultEndDate" readonly="readonly" class="datepicker date text Ty2"
                                                                           style="width:198px;" placeholder="날짜를 선택하세요" /><br />
                </div>
                <div class="btns" style=" float:right;">
                    <a class="btn blue" id="btn-down-excel">기초조사서 엑셀 일괄다운로드</a>
                </div>
            </div>

            <div style="float:left; width:100%; margin-bottom:5px; padding:20px; background-color:#f9f8f8;">
                <select style="float:left; margin-left:10px;" id="sltState">
                    <option value="1">학생명</option>
                    <option value="2">상담교사</option>
                    <option value="3">상담희망일</option>
                </select>
                <input type="text" id="txtKeyword" style="float:left; margin-left:10px;" />
                <div style="float:left; margin-left:10px;" class="btns"><a id="btn_search" class="btn  blue">검색</a></div>
                <div style="float:left; margin-left:10px;" class="btns"><a id="btn_all" class="btn  blue">전체</a></div>
            </div>
        }

        <div class="registerform">
            <div class="divider"></div>

            <div class="divider">

            </div>
            <div>
                @Html.Partial("../Shared/Partial/_List")
            </div>
            <div class="divider"></div>
        </div>
    </div>
</div>