Geumcheon.Web.Consult/Models/Reply.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Geumcheon.Web.Consult.Models
{
    public class Reply
    {
        public int ApplicationIdx { get; set; }
        public int TeacherIdx { get; set; }
        public string Note { get; set; }
        public string ReplyNote { get; set; }
        public string Progress { get; set; }


        public string ProgressName
        {
            get
            {
                string rVal = string.Empty;
                switch (Progress)
                {
                    case "R":
                        {
                            rVal = "대기중";
                            break;
                        }
                    case "I":
                        {
                            rVal = "작성중";
                            break;
                        }
                    case "C":
                        {
                            rVal = "상담완료";
                            break;
                        }
                }
                return rVal;
            }
        }

        public DateTime ReplyDate { get; set; }
    }
}

Geumcheon.Web.Consult/Models/Schedule.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Geumcheon.Web.Consult.Models
{
    public class Schedule
    {
        public int ScheduleIdx { get; set; }
        public int ApplicaionIdx { get; set; }
        public int ConsultTimeIdx { get; set; }

        public string ConsultDate { get; set; }
        public string ConsultTime { get; set; }
    }
}

Geumcheon.Web.Consult/Controllers/ConsultController.cs
using Geumcheon.Web.Consult.Models;
using Microsoft.AspNet.Identity;
using Microsoft.Owin.Security;
using System.Security.Claims;
using System.Threading.Tasks;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;
using System.Web.Security;
using Geumcheon.Web.Core.ViewModel;
using Geumcheon.Web.Core.Entity;
using Geumcheon.Web.Core.Repository;
using Geumcheon.Web.Consult.App_Start;

namespace Geumcheon.Web.Consult.Controllers
{
    public class ConsultController : Controller
    {
        static string _COMPANY_CODE = "0001";
        static int _PAGESIZE = 15;
        protected override void OnActionExecuting(ActionExecutingContext filterContext)
        {
            string actionName = filterContext.ActionDescriptor.ActionName.ToLower();
            string controllerName = filterContext.ActionDescriptor.ControllerDescriptor.ControllerName.ToLower();

            base.OnActionExecuting(filterContext);

        }

        public string SetTitle(string w,bool isBehind=true)
        {
            if (isBehind)
            {
                if (w == "B")
                {
                    return "온라인 상담 - ";
                }
                else if (w == "O")
                {
                    return "온라인 컨설팅 - ";
                }
                else if (w == "V")
                {
                    return "화상 컨설팅 - ";
                }
                else if (w == "I")
                {
                    return "대면 컨설팅 - ";
                }
                else
                {
                    return "전화 상담 - ";
                }
            }
            else
            {
                if (w == "B")
                {
                    return " - 온라인 상담";
                }
                else if (w == "O")
                {
                    return " - 온라인 컨설팅";
                }
                else if (w == "V")
                {
                    return " - 화상 컨설팅";
                }
                else if (w == "I")
                {
                    return " - 대면 컨설팅";
                }
                else
                {
                    return " - 전화 상담";
                }
            }
        }

        public string SetNavigation(string w, string roll=null)
        {
            string rVal = string.Empty;
            switch (w)
            {
                case "B":
                    {
                        rVal = "BOARD";
                        break;
                    }
                case "T":
                    {
                        rVal = "TEL";
                        break;
                    }
            }
            return rVal;
        }

        // GET: Consult
        public ActionResult Index(string w="B",int page=1,SearchInfo searchInfo = null)
        {

            ViewModelList<EntranceRequest, SearchInfo> model = new ViewModelList<EntranceRequest, SearchInfo>()
            {
                Entities = new List<EntranceRequest>(),
                Search = new SearchInfo(),
                PagingInfo = new PagingInfo(page, _PAGESIZE, 0, searchInfo.OrderType)
            };

            if (searchInfo.ConsultWay != null)
            {
                w = searchInfo.ConsultWay;
            }
            
            model.Search.CompanyCode = _COMPANY_CODE;
            model.Search.ConsultWay = w;
            model.Search.Name = searchInfo.Name;
            model.Search.TeacherId = searchInfo.TeacherId;
            
            //model.Search.SearchType = search.SearchType;

            ConsultRepository.Instance.EntranceRequestSelectPaging(model);
            model.Search.Name = searchInfo.Name;
            model.Search.TeacherId = searchInfo.TeacherId;
            model.Search.OrderType = searchInfo.OrderType;

            ViewBag.ConsultWay = w;
            
            if (_identity.Roll == null)
            {
                ViewBag.Title = SetTitle(w).Replace("-", "");                
            }
            else
            {
                if (_identity.Roll.ToString() == "CONSULT")
                {
                    ViewBag.Title = SetTitle(w) + "신청목록";
                }
                else
                {
                    ViewBag.Title = SetTitle(w).Replace("-", "");
                }
            }
            ViewBag.Navigation = SetNavigation(w);
            return View(model);

        }

        public ActionResult Admin(string w="O", int page = 1, int state = 0, string keyword = "" )
        {
            ViewModelList<EntranceRequest, SearchInfo> model = new ViewModelList<EntranceRequest, SearchInfo>()
            {
                Entities = new List<EntranceRequest>(),
                Search = new SearchInfo(),
                PagingInfo = new PagingInfo(page, _PAGESIZE, 0)
            };
            model.Search.CompanyCode = _COMPANY_CODE;
            model.Search.ConsultWay = w;
            model.Search.SearchType = state.ToString();
            model.Search.SearchText = keyword;
            ConsultRepository.Instance.EntranceRequestSelectPaging(model);

           List<Teacher> lstTeacher =  ConsultRepository.Instance.GetTeacher(_COMPANY_CODE);

            ViewBag.Teacher = lstTeacher;
            ViewBag.ConsultWay = w;
            ViewBag.Title =  "교사관리"+ SetTitle(w, false);
            ViewBag.Navigation = "M_"+SetNavigation(w);
            return View(model);
        }

        public ActionResult Form(string w="B",int idx = 0)
        {
            ViewBag.Title = SetTitle(w) + "상담입력";
            Application application = new Application();
            if (idx > 0)
            {
                application = ConsultRepository.Instance.GetApplicationForStudent(_identity.ApplicationIdx, _identity.Password);
                ViewBag.ConsultWay = application.ConsultWay;
                ViewBag.ApplicationIdx = application.ApplicationIdx;
                if (application.ConsultWay == "B")
                {
                    ViewBag.ConsultDate = "";
                    ViewBag.ConsultTimeIdx = "";
                }
                else
                {
                    ViewBag.ConsultDate = application.Schedule.ConsultDate;
                    ViewBag.ConsultTimeIdx = application.Schedule.ConsultTimeIdx;
                    ViewBag.ConsultTime = application.Schedule.ConsultTime;
                }
            }
            else
            {
                ViewBag.ConsultWay = w;
                ViewBag.ApplicationIdx = 0;
                ViewBag.ConsultDate = "";
                ViewBag.ConsultTimeIdx = "";
                ViewBag.ConsultTime = "";

            }

            //application.ApplicationIdx = 0;
            ViewBag.Navigation = SetNavigation(w);
            return View(application);
        }

        public ActionResult Detail(int idx)
        {
            Application application = new Application();
            if (_identity.Roll == "STUDENT" || _identity.Roll == "PARENT")
            {
                if (idx > 0)
                {
                    application = ConsultRepository.Instance.GetApplicationForStudent(_identity.ApplicationIdx, _identity.Password);
                    ViewBag.ConsultWay = application.ConsultWay;
                }
                else
                {

                }
            }
            else
            {
                application = ConsultRepository.Instance.GetApplicationByApplicationIdx(idx);
                
                ViewBag.ConsultWay = application.ConsultWay;
            }

            ViewBag.Title = SetTitle(application.ConsultWay) + "상담내용 상세보기";
            ViewBag.Navigation = SetNavigation(application.ConsultWay);
            return View(application);
            
        }

        public ActionResult Reply(string w, int idx = 0)
        {
            Reply reply = new Reply();
            if(_identity.Roll == "CONSULT")
            {
                reply =  ConsultRepository.Instance.GetReply(idx, _identity.ConsultId);
            }
            if (w == "B")
            {
                ViewBag.Title = "상담입력";
            }
            else
            {
                ViewBag.Title = "상담보고서 작성";
            }
            ViewBag.ConsultWay = w;
            ViewBag.Navigation = SetNavigation(w);
            return View(reply);
        }

        public ActionResult Info()
        {
            ViewBag.Title = "온라인상담실 이용안내";
            ViewBag.Navigation = "INFO";
            return View();
        }

        public ActionResult Notice()
        {
            return View();
        }

        [FPAuthorize(Roles = "GEUMCHEON")]
        public ActionResult ScheduleView(int idx=1)
        {
            if(_identity.ConsultId != "future")
            {
                idx = Convert.ToInt32(_identity.TeacherIdx);
            }
            else
            {
                List<Teacher> lstTeacher = ConsultRepository.Instance.GetTeacher(_COMPANY_CODE);
                ViewBag.Teacher = lstTeacher;
            }

            ViewBag.TeacherIdx = idx;
            List<ScheduleTime> lstScheduleTime = new List<ScheduleTime>();
            lstScheduleTime = ConsultRepository.Instance.GetScheduleTimeDetail("0001", idx);



            

            var jsMaster = new JavaScriptSerializer();
            string jsonMaster = jsMaster.Serialize(lstScheduleTime);

            ViewBag.ConsultTime = jsonMaster;
            ViewBag.TeacherIdx = idx;
            ViewBag.Title = "스케쥴관리";
            ViewBag.Navigation = "SCHEDULE";
            return View();
        }

        [FPAuthorize(Roles = "GEUMCHEON")]
        [HttpPost]
        public ActionResult GetAbleDate()
        {
            string ableDate = ConsultRepository.Instance.GetScheduleDate(_COMPANY_CODE,_identity.SchoolType);
            return Json(new
            {
                jsonMsg = ableDate
            });
        }

        [FPAuthorize(Roles = "GEUMCHEON")]

Geumcheon.Web.Consult/Views/Consult/Login.cshtml
@{
    ViewBag.Title = "Login";
}

Geumcheon.Web.Consult/Views/Consult/Notice.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section Javascript
{

}

Geumcheon.Web.Consult/Views/Consult/Reply.cshtml
@using Geumcheon.Web.Consult.Models
@using Geumcheon.Web.Core.Entity
@model Reply
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@section Javascript
{
    <script>
    $(document).ready(function () {
        $("#ifrmEditor").on("load", function () {
                setTimeout(function () {
                    var iframe1 = document.getElementById("ifrmEditor");
                    var html = $("#Note").val();
                    iframe1.contentWindow.pasteHTML(html);
                }, 1000);
            });
        //alert('tttt');
        $("#slt-progress").val($("#Progress").val());
        $("#btn-reply-save").click(function () {
            //alert('test');
            fnSave();
        });
    });

    fnSave = function () {
        //var iframe1 = document.getElementById("ifrmEditor");
        //var state = $("#sltState").val();
        //var note = iframe1.contentWindow.showHTML();
        //var isSecret = "1";
        //var a_idx = $IDX;

        var iframe1 = document.getElementById("ifrmEditor");
        var note = iframe1.contentWindow.showHTML();

        if ($("#Progress").val() == 'C' && '@ViewBag.ConsultWay' == 'B' ) {
            if (confirm("상담완료 상태로 저장하시면 학생에게 즉시 답변이 공개됩니다.\r실행하시겠습니까?")) {
                $("#Note").val(note);
                $("#CreateForm").submit();
            }
        }
        else {
            $("#Note").val(note);
            $("#CreateForm").submit();
        }

    }



    fnCancel = function () {
        //document.location.href = "Detail?OP1=" + @ViewBag.IsOnline + "&PK=" + $IDX;
        }

        $("#CreateForm").ajaxForm({
            dataType: 'json',
            beforeSubmit: function () {
            },
            success: function (json) {
                //$("#CreateForm").isLoading("hide");

                if (json.ok) {
                    location.href = "detail?idx=@Model.ApplicationIdx";
                    //return true
                }
                else {
                    alert('저장에실패했습니다');
                    //return false;
                }
            },
            error: function () {
                //return false;
                //$("#CreateForm").isLoading("hide");
            }

        });
    </script>
}
@using (Html.BeginForm("InsertReply", "Consult", FormMethod.Post, new { @id = "CreateForm", enctype = "multipart/form-data" }))
{
    @Html.HiddenFor(x => x.ApplicationIdx)
    @Html.HiddenFor(x => x.Note)
    if (ViewBag.ConsultWay == "O")
    {
        <div style="line-height:20px; margin-bottom:20px;">
            <img class="ico_required" src="/Resources/images/common/ico_required.png">상담내용 작성시, 처리상태를 <상담중>
                에 설정하고 저장하면 ‘임시저장’ 되어 답변 수정이 가능하지만, <상담완료>
                    로 설정하고 저장하면 ‘답변완료’로 즉시 답변이 노출되므로, 수정이 불가하니 유의해주세요.
                    <br />
        </div>
    }
    else
    {
        <div style="padding:2%;">
            <ul style="list-style-type:decimal-leading-zero;">
                <li>
                    상담보고서는 상담 즉시 작성해주세요.(상담일로부터 최소 2일 이내)
                </li>
                <li>
                    처리상태를 <작성중>으로 설정하고 저장하면 수정이 가능하지만, <작성완료>로 설정하고 저장하면, 최종 제출되어 수정이 불가하니 유의해주세요.
                </li>
                <li>
                    학생과 전화 상담했던 내용을 기록해주시면 감사하겠습니다.
                </li>
                <li>
                    4. 상담보고서 작성은 1) 질문1~ 질문N까지 각 질문에 대해 주셨던 답변2) 학생 및 학부모의 건의사항    3) 컨설턴트의 건의사항 및 기타 의 순으로 작성해주시면 되겠습니다.
                </li>
            </ul>
        </div>
    }
    <div class="common_form">
        <table class="form_tbl">
            <colgroup>
                <col style="width: 20%;">
                <col style="width: 80%;">
            </colgroup>
            <tbody>
                <tr class="top">
                    <th>등록자</th>
                    <td>   @_identity.ConsultId</td>
                </tr>
                <tr>
                    <th>처리상태</th>
                    <td>
                        @if (ViewBag.ConsultWay == "O")
                        {
                            @Html.DropDownListFor(x => x.Progress, (SelectList)DropDownData.PrgressItem(), new { @class = "select Ty3", @style = "width:80%;" })
                        }
                        else
                        {
                            @Html.DropDownListFor(x => x.Progress, (SelectList)DropDownData.PrgressItem_T(), new { @class = "select Ty3", @style = "width:80%;" })
                        }
                    </td>
                </tr>

                <tr>
                    <td colspan="4" height="500px;" style="padding:0px !important;">
                        <iframe src="~/Editor/SmartEditor2.html" frameborder="0" style="width:100%; height:500px" scrolling="no" id="ifrmEditor"></iframe>
                    </td>
                </tr>
            </tbody>
        </table>
        <div class="btn_a right no-print">
            <a href="#" class="btn white" id="btn-reply-save" style="padding:0px;">작성취소</a>
            <a href="#" class="btn blue" id="btn-reply-cancel" style="padding:0px;" onclick="fnSave();">저장하기</a>
        </div>
    </div>
}

Geumcheon.Web.Consult/Views/Consult/ScheduleView.cshtml
@using PagedList.Mvc
@using Geumcheon.Web.Consult.Models
@using Geumcheon.Web.Core.Entity
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<link rel="stylesheet" href="~/Resources/css/tab.css" type="text/css" />
<style>
    table {
        /*width: 100%;*/
        border: 1px solid #444444;
        border-collapse: collapse;
        /*overflow:scroll;*/
    }

    th, td {
        border: 1px solid #444444;
        width: 100px;
        height: 20px;
    }

    .slt-schedule {
        height: 20px;
        line-height: 20px;
        padding: 0px;
        border: 0px;
    }

    .no-schedule {
        /*background-color : #dcd9d9;*/
        color: red;
        /*font-weight:bold;*/
        text-align: center;
        cursor: pointer;
    }

    .yes-schedule {
        /*background-color: #8bd3e4;*/
        color: blue;
        text-align: center;
        cursor: pointer;
    }

    .yes-scheduled {
        background-color: #ffd800;
        text-align: center;
        /*cursor: pointer;*/
        font-weight: bold;
    }
</style>

<script type="text/javascript">
    var dateItemArray = new Array();
    $(document).ready(function () {

        $(".tab-menu li").click(function () {

        });

        var timeArray = ['09:00~10:00'
            , '10:00~11:00'
            , '11:00~12:00'
            , '12:00~13:00'
            , '13:00~14:00'
            , '14:00~15:00'
            , '15:00~16:00'
            , '16:00~17:00'
            , '17:00~18:00'
            , '18:00~19:00'
            , '19:00~20:00'
            , '20:00~21:00'
            , '21:00~22:00'
        ]

        var scheduleHtml = "";
        var timeHtml = "";
        //var i = 251;
        var i = 1;
        $.each(timeArray, function (key, value) {
            //i = (key + 251);
            i = (key + 1);
            //var html = "<tr><td>" + value + "</td>"
            //var html = "<tr><td>" + value + "</td>"
            var html = "<tr>"
            var time_html = "<tr style=\"height:20px; background-color:#7eb980; text-align:center; color:white;\"><td>"+value+"</td></tr>"

            html+="</tr>"
            scheduleHtml += html;
            timeHtml += time_html;

        });

        var date = $("#sltMonth").val();
        dateItemArray = fnMakeScheduleTable(date, '');
        $("#schedule").append(scheduleHtml);
        $("#time").append(timeHtml);


        $("#slt-teacher").change(function () {
            location.href = "scheduleview?idx=" + $(this).val();
        })

        $("#sltMonth").change(function () {

            $.each($("#schedule").find("tr"), function (index, val) {
                if (!$(this).hasClass("schedule-frame")) {
                    $(this).remove();    
                }
            });

            $.each($("#time").find("tr"), function (index, val) {

                //$(this).remove();
                if (!$(this).hasClass("schedule-frame")) {
                    $(this).remove();
                }
            });

            $.each($(".schedule-frame").find("td"), function (index, val) {
                if (!$(this).hasClass("notdelete")) {
                    $(this).remove();
                }
            });
            var scheduleHtml = "";
            var timeHtml = "";
            $.each(timeArray, function (key, value) {
                //i = (key + 251);
                i = (key + 1);
                //var html = "<tr><td>" + value + "</td>"
                //var html = "<tr><td>" + value + "</td>"
                var html = "<tr>"
                var time_html = "<tr style=\"height:20px; background-color:#7eb980; text-align:center; color:white;\"><td>" + value + "</td></tr>"

                html += "</tr>"
                scheduleHtml += html;
                timeHtml += time_html;

            });
            dateItemArray = fnMakeScheduleTable($(this).val(), '');
            $("#schedule").append(scheduleHtml);           
            $("#time").append(timeHtml);
        })
    });

    fnSetDetailSchedule =function(t,ct,isc) {
        var teacherIdx = 0;
        if ("@_identity.ConsultId" == "future") {
            teacherIdx = $("#slt-teacher").val();
        }
        else {
            teacherIdx = "@_identity.TeacherIdx"
        }     

        mlDebug(teacherIdx);
		$.ajax({
            type: "POST",
            contentType: "application/json; charset=UTF-8",
            dataType: "json",
            data: JSON.stringify({
                  'ct': ct
                , 'isc': isc
                , 't': teacherIdx
            }),
            url: '@Url.Action("ModifyDetail", "Consult")',
            success: function (msg) {
				//var result = msg.ok;
                //if (!result) {
                //    alert('저장에 실패했습니다')
                //}                
            },
            error: function (xhr, msg) {alert('eeeeeeeeeee');},
        });
    }

    fnMakeScheduleTable = function (date, way) {
        var dateItemArray = new Array();
        var timeItemArray = new Array();
        $.ajax({
            type: "POST",
            contentType: "application/json; charset=UTF-8",
            dataType: "json",
            data: JSON.stringify({
                'date': date
                , 'way': 'I'
            }),
            url: '@Url.Action("GetSehduleTable", "Consult")'
        }).done(function (msg) {
                //msg.jsonSheduleDate.forEach(element => alert(element));
            dateItemArray = msg.jsonSheduleDate;
            timeItemArray = msg.jsonSheduleTime;
            $.each(dateItemArray, function (key, value) {
                $("#consultDate").append("<td>" + value.ConsultDate + "</td>")
            });


            $.each(timeItemArray, function (key, value) {
                //alert(value.ConsultTimeIdx)

            });


            var rowIdx = 1;
            $.each(timeItemArray, function (key, value) {
                //alert(key);
                var tr = $("#schedule").find("tbody").find("tr").get(rowIdx);
                $(tr).append("<td class=\"td-schedule no-schedule\" id=\"idx-" + value.ConsultTimeIdx + "\"><span is-confirmed=\"0\">X</span></td>");

                rowIdx++;
                if (rowIdx == 14) {
                    rowIdx = 1;
                }
            });

            $(".td-schedule").click(function () {
                var isConfirmed = $(this).find("span").attr("is-confirmed");
                var consultTimeidx = $(this).attr("id").replace("idx-", "");
                var teacherIdx = '1';

                if (isConfirmed == "99") {
                    return;
                }

                if (isConfirmed == "0") {
                    isConfirmed = "1"

                    $(this).find("span").text("●");
                    $(this).removeClass("no-schedule");
                    $(this).addClass("yes-schedule");
                    $(this).find("span").attr("is-confirmed", "1");
                }
                else {
                    isConfirmed = "0"

                    $(this).find("span").text("X");
                    $(this).removeClass("yes-schedule");
                    $(this).addClass("no-schedule");
                    $(this).find("span").attr("is-confirmed", "0");
                }
                fnSetDetailSchedule(teacherIdx, consultTimeidx, isConfirmed);

            });



            var json = '@ViewBag.ConsultTime'.replace(/&quot;/g, '"');
            var jsonObj = JSON.parse(json);

            $.each(jsonObj, function (key, value) {
                if (value.ScheduledTimeIdx > 0) {
                    $("#idx-" + value.ConsultTimeIdx).find("span").text("상담예약");
                    $("#idx-" + value.ConsultTimeIdx).removeClass("no-schedule");
                    $("#idx-" + value.ConsultTimeIdx).removeClass("td-schedule");
                    $("#idx-" + value.ConsultTimeIdx).addClass("yes-scheduled");
                    $("#idx-" + value.ConsultTimeIdx).find("span").attr("is-confirmed", "99");
                }

                else {
                    $("#idx-" + value.ConsultTimeIdx).find("span").text("●");
                    $("#idx-" + value.ConsultTimeIdx).removeClass("no-schedule");
                    $("#idx-" + value.ConsultTimeIdx).addClass("yes-schedule");
                    $("#idx-" + value.ConsultTimeIdx).find("span").attr("is-confirmed", "1");
                }
            });
            }).error(function (xhr, msg) {
                alert(msg+'11');
            });
        return dateItemArray;
    }
</script>

@if (_identity.Roll == "CONSULT" && _identity.ConsultId == "future")
{
    <div>
        <span style="margin-left:5px;font-weight:bold;">교사선택:</span>
        <select style="width:500px; margin-left:5px;" id="slt-teacher">            
            @foreach (var t in ViewBag.Teacher)
            {
                if(ViewBag.TeacherIdx == t.TeacherIdx)
                {
                    <option value="@t.TeacherIdx" selected="selected"> @t.TeacherName (@t.LoginId)</option>                                     
                }
                else
                {
                    <option value="@t.TeacherIdx"> @t.TeacherName (@t.LoginId)</option>                                     
                }
                
            }
        </select>
    </div>
    <hr />
}

<div style="margin-left:10px;  min-width:900px;max-width:900px;">

    <select id="sltMonth" style="float:right;">
        <option value="2020-5">2020년-05월</option>
        <option value="2020-6">2020년-06월</option>
        <option value="2020-7">2020년-07월</option>
        <option value="2020-8">2020년-08월</option>
        <option value="2020-9">2020년-09월</option>
        <option value="2020-10">2020년-10월</option>
        <option value="2020-11">2020년-11월</option>
        <option value="2020-12">2020년-12월</option>
    </select>
    <span style="font-weight:bold;float:right; margin-right:10px;">년-월선택</span>
</div>
<div style="width:100%; padding:3px; flex-direction:row;display:flex;">
    <div style="width:140px;">
        <table id="time">
            <tr style="height:27px;text-align: center;" class="schedule-frame">
                <td style="background-color:#7fa9ce;color:white;font-weight:bold;" class="notdelete">
                    
                </td>
            </tr>
        </table>
    </div>


    <div style="overflow:auto; max-width:900px !important;">
        <table style="border:1px solid" id="schedule" >
            <tr id="consultDate" style="text-align: center;background-color:#7fa9ce;color: white;" class="schedule-frame">            
            </tr>


        </table>
    </div>
</div>