Geumcheon.Web.Consult/Controllers/MyPageController.cs
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Geumcheon.Web.Core.ViewModel;
using Geumcheon.Web.Core.Entity;
using Geumcheon.Web.Core.Repository;
using System.Web.Script.Serialization;
using Newtonsoft.Json.Linq;
using Geumcheon.Web.Consult.Models;
using System.IO;
using Geumcheon.Web.Consult.App_Start;

namespace Geumcheon.Web.Consult.Controllers
{
    public class MyPageController : Controller
    {
        static string _COMPANY_CODE = "0001";
        static int _PAGESIZE = 15;

        // GET: Score
        public ActionResult Index()
        {
            return View();
        }

        [FPAuthorize(Roles = "GEUMCHEON")]
        public ActionResult BasicInfo(string writerType = "p", int memberIdx = 0)
        {
            DefaultInfo model = new DefaultInfo();
            ViewBag.WriterType = writerType.ToUpper();
            if (_identity.Roll == "STUDENT" || _identity.Roll == "PARENT")
            {
                model = MyPageRepository.Instance.GetDefaultInfo(Convert.ToInt32(_identity.MemberIdx), writerType.ToUpper(), true);
            }
            else
            {
                model = MyPageRepository.Instance.GetDefaultInfo(memberIdx, writerType.ToUpper(), true);
            }
            
            if (model.ApplyUniversityItem==null)
            {
                ViewBag.UnivJson = string.Empty;               
            }
            else
            {
                var jsMaster = new JavaScriptSerializer();
                string jsonMaster = jsMaster.Serialize(model.ApplyUniversityItem);
                ViewBag.UnivJson = jsonMaster;
            }
            if (model.Answer==null)
            {
                ViewBag.AnswerJson = string.Empty;
            }
            else
            {
                ViewBag.AnswerJson = model.Answer.AnswerJson;
            }
            

            return View();
        }
        [FPAuthorize(Roles = "GEUMCHEON")]
        public ActionResult FileUpload()
        {
            List<Files> lstFileInfo = new List<Files>();
            lstFileInfo = MyPageRepository.Instance.GetFiles(_identity.MemberIdx);

            return View(lstFileInfo);
        }

        [FPAuthorize(Roles = "GEUMCHEON")]
        public ActionResult Moi()
        {
            string info = MyPageRepository.Instance.GetMoiInfo(Convert.ToInt32(_identity.MemberIdx));
            ViewBag.TestInfo = info;
            return View();
        }

        [FPAuthorize(Roles = "GEUMCHEON")]
        public ActionResult Nesin()
        {
            Nesin model = MyPageRepository.Instance.GetNesin(Convert.ToInt32(_identity.MemberIdx));
            if(model == null)
            {
                ViewBag.IsCreate = 1;
                model = new Nesin();
            }
            else
            {
                ViewBag.IsCreate = 0;
            }
            return View(model);
        }

        [FPAuthorize(Roles = "GEUMCHEON")]
        public ActionResult SmartTest()
        {
            return View();
        }

        [FPAuthorize(Roles = "GEUMCHEON")]
        public ActionResult RequestList()
        {
            ViewBag.Navigation = "REQUESTLIST";
            return View();
        }

        [FPAuthorize(Roles = "GEUMCHEON")]
        public ActionResult StudentRecord()
        {
            ViewBag.Navigation = "REQUESTLIST";
            List<Files> file = MyPageRepository.Instance.GetFiles(_identity.MemberIdx);
            
            return View(file);
        }

        [FPAuthorize(Roles = "GEUMCHEON")]
        public ActionResult Survey()
        {
            return View();
        }

        [FPAuthorize(Roles = "GEUMCHEON")]
        public ActionResult SmartCoaching()
        {
            ViewBag.Navigation = "REQUESTLIST";
            string rVal = MyPageRepository.Instance.GetConsultSmartCoaching(_identity.MemberIdx);
            if (string.IsNullOrEmpty(rVal))
            {
                ViewBag.ID = "NOT FOUND";
                ViewBag.PWD = "NOT FOUND";
            }
            else
            {

                try
                {
                    ViewBag.ID = rVal.Split('/')[0];
                    ViewBag.PWD = rVal.Split('/')[1];
                }
                catch
                {
                    ViewBag.ID = "NOT FOUND";
                    ViewBag.PWD = "NOT FOUND";
                }
            }
            return View();
        }




        //[HttpPost]
        //public ActionResult UploadFile()
        //{
        //    string[] arrFileType = Request.Form["file_type"].ToString().Split(',');
        //    List<Files> entities = new List<Files>();
        //    try
        //    {
        //        int i = 0;
        //        foreach (string fle in Request.Files)
        //        {
        //            HttpPostedFileBase file = Request.Files[i];
        //            int lectureSeq = Convert.ToInt32(Request.Form["___memberidx___"].ToString());
        //            string filetype = arrFileType[i];
        //            string fileId = Guid.NewGuid().ToString();
        //            string fileName = file.FileName;
        //            i++;

        //            string pathForSaving = Server.MapPath("~/Uploads");
        //            file.SaveAs(Path.Combine(pathForSaving, fileId));

        //            Files entity = new Files();
        //            entity.MemberIdx = _identity.MemberIdx;
        //            entity.FileID = fileId;
        //            entity.FileName = fileName;
        //            entity.FileSize = file.ContentLength.ToString();
        //            entity.FileType = filetype;

        //            entities.Add(entity);

        //        }

        //        int rVal = MyPageRepository.Instance.FilesUpsert(entities[0]);

        //        if (rVal == 1)
        //        {
        //            return Json(new
        //            {
        //                result = "T"
        //            });
        //        }
        //        else
        //        {
        //            return Json(new
        //            {
        //                result = "F"
        //            });
        //        }
        //    }
        //    catch (Exception ex)
        //    {
        //        return Json(new
        //        {
        //            result = "F"
        //        });
        //    }
        //}
        [HttpPost]
        [Authorize(Roles = "GEUMCHEON")]
        public ActionResult UploadFile()
        {
            string updateFileid = Request.Form["___update_file___"];
            string uploadId = _identity.MemberIdx;    


            Files updateFiles = new Files();
            if (string.IsNullOrEmpty(updateFileid))
            {
                updateFileid = "";
            }
            updateFiles.FileID = "|" + updateFileid.Replace(",", "|") + "|";
            updateFiles.MemberIdx = uploadId;

            try
            {
                List<Files> list = new List<Files>();
                List<HttpPostedFileBase> filelist = new List<HttpPostedFileBase>();
                int i = 0;
                foreach (string fileName in Request.Files)
                {
                    HttpPostedFileBase file = Request.Files[i];
                    try
                    {
                        string fileId = Guid.NewGuid().ToString();
                        list.Add(new Files
                        {
                            FileID = fileId
                            ,
                            FileName = file.FileName
                            ,
                            FileSize = file.ContentLength.ToString()

                        });
                        string pathForSaving = Server.MapPath("~/Uploads");
                        file.SaveAs(Path.Combine(pathForSaving, fileId));                        
                        filelist.Add(file);
                        i++;
                    }
                    catch
                    {

                    }
                }


                foreach (Files file in list)
                {
                    file.MemberIdx = uploadId;
                }

                //if (list.Count() > 0)
                //{
                //    FileSave(list, filelist);
                //}
                int rVal = MyPageRepository.Instance.FileInsert(list, updateFiles);
                if (rVal > 0)
                {
                    return Json(new
                    {
                        result = "T"
                    });
                }
                else
                {
                    return Json(new
                    {
                        result = "F"
                    });
                }
            }

            catch (Exception ex)
            {
                return Json(new
                {
                    result = ex.Message
                });
            }

        }

        [HttpPost]
        public JsonResult ModifyDefailtInfo(string writerType, string answer, string univitem)
        {
            Answer ans= new Answer
            {
                MemberIdx = Convert.ToInt32(_identity.MemberIdx)
            ,    WriterType = writerType
            ,    AnswerJson = answer
            };
            DataTable dtUnivItem = JsonConvert.DeserializeObject<DataTable>(univitem);

            DefaultInfo defaultInfo = new DefaultInfo
            {
                Answer = ans,
                tbUnivesity = dtUnivItem
            };

            int result = MyPageRepository.Instance.setDefaultInfo(defaultInfo);

            if (result > 0)
            {
                return Json(new { ok = true });
            }
            else
            {
                return Json(new { ok = false });
            }
        }

        [HttpPost]
        public JsonResult ModifyAnswer(string writerType, string answer)
        {

Geumcheon.Web.Consult/Views/Shared/Partial/_ConsulDataNavigation.cshtml
<style>
    .page_tab ul {
        border-bottom-color: #02523a;
        border-bottom-width: 1px;
        border-bottom-style: solid;
        -ms-zoom: 1;
    }

        .page_tab ul::after {
            clear: both;
            display: block;
            content: "";
        }

        .page_tab ul li {
            background: rgb(245, 245, 245);
            border-width: 1px 1px 0px;
            border-style: solid solid none;
            border-color: rgb(195, 195, 195) rgb(195, 195, 195) currentColor;
            border-image: none;
            width: 164px;
            float: left;
            list-style: none;
        }

            .page_tab ul li a {
                width: 100%;
                height: 30px;
                text-align: center;
                color: rgb(102, 102, 102);
                line-height: 30px;
                font-size: 14px;
                display: block;
                text-decoration: none;
            }

            .page_tab ul li.curr {
                background: rgb(255, 255, 255);
                border-width: 1px 1px 0px;
                border-style: solid solid none;
                border-color: #02523a #02523a currentColor;
                border-image: none;
            }

                .page_tab ul li.curr a {
                    top: 1px;
                    color: #02523a;
                    border-bottom-color: rgb(255, 255, 255);
                    border-bottom-width: 1px;
                    border-bottom-style: solid;
                    position: relative;
                }

    .sel {
        font-weight: bold;
        color: white;
        background-color: #EE7855;
    }

    th {
        font-weight: bold !important;
    }

    .writer {
        font-weight: bold;
    }

    .thead {
        background-color: #f2f2f2;
        font-weight: bold !important;
    }

    .thead-dark {
        background-color: #e7e7e7;
        font-weight: bold !important;
    }

    .answer {
        width: 98%;
    }

    .borderTop {
        border-top: 1px solid black;
    }

    .borderBottom {
        border-bottom: 1px solid black;
    }
</style>
<link rel="stylesheet" href="~/Resources/css/tab.css" type="text/css" />
<script>
    $(document).ready(function () {
        setNavigationItem('BASICINFO_P');

        $(".tab-menu li").click(function () {
            var menuname = $(this).attr("menu");
            setNavigationItem(menuname);
        });
    });

    setNavigationItem = function (menename) {
        var obj = $(".tab-menu li").get(0);
        switch (menename)
        {
            case 'BASICINFO_P':{
                obj = $(".tab-menu li").get(0);
                break;
            }
            case 'BASICINFO_S': {
                obj = $(".tab-menu li").get(1);
                break;
            }
            case 'NESIN': {
                obj = $(".tab-menu li").get(2);
                break;
            }
            case 'MOI': {
                obj = $(".tab-menu li").get(3);
                break;
            }
            case 'STUDENTRECORD': {
                obj = $(".tab-menu li").get(4);
                break;
            }
        }
        $(".tab-menu li").removeClass("selected");
        $(obj).addClass("selected");
    }
</script>

Geumcheon.Web.Consult/Views/Shared/Partial/_Info_C.cshtml
@if (ViewBag.ConsultWay == "V")
{
    <h1 style="padding:0px 8px; color:red;">| 처리상태 |</h1>
    <div class="registerdata">
        <ul style="list-style:square ; margin-left:25px;">
            <li>승인대기 : 신청이 접수 된 상태입니다</li>
            <li>신청승인 : 접수 된 신청에 대해 상담 선생님이 배정 된 상태입니다.</li>
            <li>상담완료 : 상담이 완료 된 상태입니다.</li>
        </ul>
    </div>
    <div class="divider"></div>
    <h1 style="padding:0px 8px;">| 주의사항 |</h1>
    <div class="registerdata" style="display:flex; align-items:center;">
        <ul style="list-style:decimal ; margin-left:25px;">
            <li>
                컨설턴트의 상담 가능 일에 신청되며, 동시간 컨설턴트가 2인 이상일때 누적 상담수가 적은 분부터 순차적으로 매칭됩니다.
                <br />(5.7일부터 신청학생 명단 확인 가능하며, 5.11-5.31일까지는 1일/1회 정도 로긴해서 신청자 매칭 확인하심 될듯함)
            </li>
            <li>
                아래 첨부된 <금천구온라인컨설팅 매뉴얼>
                    을 숙지하시고, 5/7일까지 매뉴얼 9p의 <개인회의 ID 공유/ 초대복사> 를 하여 카톡의 ‘퓨쳐플랜 1:1채팅창에 알려주세요
                    <br />운영진에서 컨설팅 할 학생들에게 사전에 해당 컨설턴트님의 회의방 입장 ID/pw를 공유하기 위함
            </li>
            <li>
                학생의 기초자료- 기초조사서(학생, 학부모용)/ 내신,모의성적/학생부(사진 또는 PDF)/심리검사(진로학습종합)-는 상담일 7-3일 이내에 확인 가능하십니다
                <br />학생들에게 최소 7일 전까지 입력을 요청하지만, 입력이 늦어질 수 있습니다. 만약, 3일전임에도 기초자료가 누락되거나 미입력된 경우, 반드시 운영진(퓨쳐플랜1:1채팅창)에 알려주세요.
            </li>
            <li>
                학생이 입력한 사전 기초자료들을 다운받거나 프린트하셔서 미리 상담준비를 마쳐주세요.(대분의 자료는 엑셀이나 PDF로 다운이 가능합니다.)
            </li>
            <li>
                통을 사용하는 분은  1. 성적엑셀 다운받기  / 2. 통>간단성적> 반 생성(‘2020.5월상담—또는 본인이 임의로 설정)’ / 3. 내려받은 성적엑셀파일을 간단성적 매뉴에 파일추가(업로드)하면 상담매뉴 사용가능(통 사용안하시는 분은 내려받은 성적파일을 보고, 반드시 오류없이 사용하시는 시스템에 입력—통 사용을 희망하시는 분은 운영진에 알려주세요. 상담기간동안 오픈해드리고 이용방법 안내해드리겠습니다. )
            </li>
            <li>
                최소 상담시작 30분 전에는 상담신청 시 학생이 제출한 궁금증 등을 중심으로 상담계획 수립과 화상컨설팅 준비를 마쳐주세요.
            </li>
            <li>
                학생의 즉각적인 문의에 대한 응답을 위해 PC에 금천구대입지원프로그램(해당 학생신청 페이지)/통/포털/어디가/커리어넷/진학상담 관련 정보 등을 켜놔주세요.
            </li>
            <li>
                최소 상담시작 상담은 반드시 주변방해가 없는 1인실에서 해주세요
            </li>
            <li>
                상담시작 10분이 지나도 학생이 화상 연결이 안되면, 운영진에게 즉시 알려주시고 접속은 중단해주세요 <br />(‘상담보고서’에 ‘부재중으로 상담완료 못함’으로 기록요망)<br /> - 18시 이후, 또는 휴일에 운영진의 즉답이 어려운 경우, 운영진이 다음날  학생과 통화하여 확인(상담준비를 이미 하셨기 때문에 1회에 한해 학생일정 재약속)
            </li>
            <li>
                상담시작 직전, 타이머를 ‘50분’ 설정 후 시작하고, 50분 초과가 안되도록 해주세요.
            </li>
            <li>
                만약, 50분 전 상담이 조기 완료된 경우, 반드시 내담자에게 '더 물어볼게 없는지. 상담을 마쳐도 되겠는지' 반드시 물은후, 마쳐주세요<br />(상담시간이 남았는데, 컨설턴트가 그냥 끊었다.. 라는 불만이 없도록)
            </li>
            <li>
                상담은 학생의 상담신청 시 제출한 궁금증부터 답변을 주시고, 이 부분이 해결된 후 추가적인 질의응답으로 진행하시면 됩니다.
            </li>
            <li>
                상담을 마칠때는 “오늘 상담이 도움이 되셨기를 바라며, 더 궁금하신 부분은 온라인 상담실에 문의하거나,  향후 화상이나 대면 컨설팅을 신청해주세요. 이후 문자로 드리는 만족도 설문지에 성실한 답변 부탁드리겠습니다. 감사합니다”라고 하십니다.
            </li>
            <li>
                상담 직후, 반드시 <상담보고서>를 제출해주세요(제출마감: 익일까지)
            </li>
            <li>
                내담자와의 상담을 통해 알게 된 일체정보(개인정보 및 상담내용 등 일체)는 어떠한 경로로도 절대 유출되어서는 안됩니다. 명심해주세요.
            </li>
            <li style="color:red">
                1:1 화상(비대면) 입시컨설팅 ZOOM 설치방법 및 프로그램 다운로드
            </li>
            <li style="list-style:none;">
                <a href="http://geumcheon.eduplan.co.kr/금천구_화상_대면_컨설팅_매뉴얼_컨설턴트.pdf" style="text-decoration:underline;cursor:pointer; color:blue">
                    [컨설턴트] ※ZOOM설치방법 PDF 파일 다운로드
                </a>
            </li>
            <li style="list-style:none;">
                <a href="https://www.zoom.us/client/latest/ZoomInstaller.exe" style="text-decoration:underline;cursor:pointer; color:blue">
                    ZOOM 프로그램 다운로드
                </a>
            </li>
        </ul>
    </div>
    <div class="divider"></div>
}

else if (ViewBag.ConsultWay == "O")
{
    <h1 style="padding:0px 8px; color:red;">| 처리상태 |</h1>
    <div class="registerdata">
        <ul style="list-style:square ; margin-left:25px;">
            <li>승인대기 : 신청이 접수 된 상태입니다</li>
            <li>신청승인 : 접수 된 신청에 대해 상담 선생님이 배정 된 상태입니다.</li>
            <li>상담완료 : 상담이 완료 된 상태입니다.</li>
        </ul>
    </div>
    <div class="divider"></div>
    <h1 style="padding:0px 8px;">| 주의사항 |</h1>
    <div class="registerdata" style="display:flex; align-items:center;">
        <ul style="list-style:decimal ; margin-left:25px;">
            <li>
                학생이 온라인 상담 신청을 올린 날로부터 48시간 이내에 배정되신 컨설턴트님은 답변을 달아주시면 됩니다. (컨설턴트는 번호순으로 자동 배정됨)
                <br />5.4일부터 신청학생 명단 확인 가능하며,  2일/1회 정도 신청자 매칭 확인하심 될듯함
            </li>
            <li>아래 첨부된 <금천구온라인컨설팅 매뉴얼>을 숙지하시고, 상담에 임해주세요</li>
            <li>
                상담시 시작문구는 “안녕하세요, 금천구 온라인 진학상담실입니다“ 로 시작하고,
                마지막에는  “질문의 답변이 충분하셨는지요. 오늘 상담이 도움이 되셨기를 바라며, 더 궁금하신 부분은 온라인 상담실에 문의하거나,  향후 화상이나 대면 컨설팅을 신청해주세요. 이후 문자로 드리는 만족도 설문지에 성실한 답변 부탁드리겠습니다. 감사합니다”라고 마무리 해주십니다.
            </li>
            <li>
                별도의 상담보고서는 없고, 학생에게 답변하신 내용이 상담보고서로 갈음됩니다.
            </li>
            <li>
                내담자와의 상담을 통해 알게 된 일체정보(개인정보 및 상담내용 등 일체)는 어떠한 경로로도 절대 유출되어서는 안됩니다. 명심해주세요.
            </li>
            <li style="list-style:none;">
                <a href="http://geumcheon.eduplan.co.kr/금천구_화상_대면_컨설팅_매뉴얼_컨설턴트.pdf" style="text-decoration:underline;cursor:pointer; color:blue">
                    [컨설턴트] ※ZOOM설치방법 PDF 파일 다운로드
                </a>
            </li>
            <li style="list-style:none;">
                <a href="https://www.zoom.us/client/latest/ZoomInstaller.exe" style="text-decoration:underline;cursor:pointer; color:blue">
                    ZOOM 프로그램 다운로드
                </a>
            </li>
        </ul>
    </div>
}
else
{
    <h1 style="padding:0px 8px; color:red;">| 처리상태 |</h1>
    <div class="registerdata">
        <ul style="list-style:square ; margin-left:25px;">
            <li>승인대기 : 신청이 접수 된 상태입니다</li>
            <li>신청승인 : 접수 된 신청에 대해 상담 선생님이 배정 된 상태입니다.</li>
            <li>상담완료 : 상담이 완료 된 상태입니다.</li>
        </ul>
    </div>
    <div class="divider"></div>
}

Geumcheon.Web.Consult/Views/Shared/Partial/_Info_S.cshtml
@if (ViewBag.ConsultWay == "O")
{
    <h1 style="padding:0px 8px;">| 신청기간 |</h1>
    <div class="registerdata">
        <ul style="list-style:square ; margin-left:25px;">
            <li>2020년 6월 1일(월) ~ 2020년 7월 17일(금)</li>
        </ul>
    </div>
    <div class="divider"></div>

    <h1 style="padding:0px 8px;">| 상담일정 |</h1>
    <div class="registerdata">
        <ul style="list-style:square ; margin-left:25px;">
            <li>2020년 8월 1일(토)</li>
        </ul>
    </div>
    <div class="divider"></div>

    <h1 style="padding:0px 8px;">| 상담 전 준비서류 |</h1>
    <div class="registerdata" style="display:flex; align-items:center;">
        <ul style="list-style:square ; margin-left:25px;">
            <li>아래의 ‘신청하기’로 상담신청 후, 상단의 <나의활동>의 <컨설팅 기초자료 입력>에서 모든 항목을 입력해야 정식으로 접수가 완료됩니다.</li>
            <li>컨설팅 1주일 전까지 기초자료를 입력하지 않았거나 누락의 경우, 예비자 학생에게 컨설팅 기회가 자동 양도되므로 주의해 주세요</li>
        </ul>
        <div class="btns" style="margin-left:8px; display:none;">
            <a href="@Url.Action("BasicInfo", "MyPage")" class="btn blue" id="modifyBtn" style="">컨설팅 기초자료 제출 바로가기</a>
        </div>
    </div>

    <div class="divider"></div>
}

Geumcheon.Web.Consult/Views/Shared/Partial/_UserDataNavigation.cshtml
<style>
    .page_tab ul {
        border-bottom-color: #02523a;
        border-bottom-width: 1px;
        border-bottom-style: solid;
        -ms-zoom: 1;
    }

        .page_tab ul::after {
            clear: both;
            display: block;
            content: "";
        }

        .page_tab ul li {
            background: rgb(245, 245, 245);
            border-width: 1px 1px 0px;
            border-style: solid solid none;
            border-color: rgb(195, 195, 195) rgb(195, 195, 195) currentColor;
            border-image: none;
            width: 164px;
            float: left;
            list-style: none;
        }

            .page_tab ul li a {
                width: 100%;
                height: 30px;
                text-align: center;
                color: rgb(102, 102, 102);
                line-height: 30px;
                font-size: 14px;
                display: block;
                text-decoration: none;
            }

            .page_tab ul li.curr {
                background: rgb(255, 255, 255);
                border-width: 1px 1px 0px;
                border-style: solid solid none;
                border-color: #02523a #02523a currentColor;
                border-image: none;
            }

                .page_tab ul li.curr a {
                    top: 1px;
                    color: #02523a;
                    border-bottom-color: rgb(255, 255, 255);
                    border-bottom-width: 1px;
                    border-bottom-style: solid;
                    position: relative;
                }

    .sel {
        font-weight: bold;
        color: white;
        background-color: #EE7855;
    }

    th {
        font-weight: bold !important;
    }

    .writer {
        font-weight: bold;
    }

    .thead {
        background-color: #f2f2f2;
        font-weight: bold !important;
    }

    .thead-dark {
        background-color: #e7e7e7;
        font-weight: bold !important;
    }

    .answer {
        width: 98%;
    }

    .borderTop {
        border-top: 1px solid black;
    }

    .borderBottom {
        border-bottom: 1px solid black;
    }
</style>
<link rel="stylesheet" href="~/Resources/css/tab.css" type="text/css" />
<script>
    $(document).ready(function () {
        var obj = $(".tab-menu li").get(0);
        switch ('@Model')
        {
            case 'BASICINFO_P':{
                obj = $(".tab-menu li").get(0);
                break;
            }
            case 'BASICINFO_S': {
                obj = $(".tab-menu li").get(1);
                break;
            }
            case 'NESIN': {
                obj = $(".tab-menu li").get(3);
                break;
            }
            case 'MOI': {
                obj = $(".tab-menu li").get(4);
                break;
            }
            case 'STUDENTRECORD': {
                obj = $(".tab-menu li").get(2);
                break;
            }
            case 'SMARTTEST': {
                obj = $(".tab-menu li").get(5);
                break;
            }

            case 'SMARTCOACHING': {
                obj = $(".tab-menu li").get(3);
                break;
            }
        }
        $(".tab-menu li").removeClass("selected");
        $(obj).addClass("selected");
    });
</script>
@if (Geumcheon.Web.Consult.Models._identity.SchoolType == "M")
{
    <div class="tab-menu-wrap" style="margin-bottom:10px;">
        <ul class="tab-menu">
            <li style="width: 25%;"><a href="BasicInfo?writerType=p">기초조사서(학부모)</a></li>
            <li class="selected" style="width: 25%;"><a href="BasicInfo?writerType=s">기초조사서(학생)</a></li>            
            <li style="width: 25%;"><a href="StudentRecord">학교생활기록부</a></li>
            <li style="width: 25%;"><a href="SmartCoaching">성적/검사</a></li>
        </ul>
    </div>
}
else
{
    <div class="tab-menu-wrap" style="margin-bottom:10px;">
        <ul class="tab-menu">
            <li style="width: 16.6%;"><a href="BasicInfo?writerType=p">기초조사서(학부모)</a></li>
            <li class="selected" style="width: 16.6%;"><a href="BasicInfo?writerType=s">기초조사서(학생)</a></li>
            <li style="width: 16.6%;"><a href="StudentRecord">학교생활기록부</a></li>
            <li style="width: 16.6%;"><a href="Nesin">내신성적</a></li>
            <li style="width: 16.6%;"><a href="Moi">모의고사성적</a></li>

            <li style="width: 16.6%;"><a href="SmartTest">검사하기</a></li>            
        </ul>
    </div>
}